### ISSUE TITLE
Asyncpg config extension

### ISSUE THREAD

**Issue by da-the-dev** [IU-Capstone-Project-2024/LAN-backend#2]
В `.env` мы храним переменную `DB_URL`. Для миграций alembic нужно, чтобы запросы были синхронными, но в коде у нас везде подразумевается асинхронное выполнение. Для этого в переменной DB_URL пишется не `postgresql//` `postgresql+asyncpg://`.

Но каждый раз это менять неистово впадлу, поэтому нужно настроить так, чтобы во всем коде подключался asyncpg, а в alembic нет

По идее, можно оставить в `.env` в покое (`postgress://`), тогда `migrations/env.py` можно доставать напрямую из переменных окружения, а в `src/config` приписывать к строчке `asyncpg`

**Comment by simelles** [comment]
done
